baseURL = 'https://koikbin.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
[[module.imports]]
    path = 'github.com/jpanther/congo/v2'

enableRobotsTXT = false  #預設為true

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

